spring.application.name=banking-lab

spring.datasource.url=jdbc:postgresql://localhost:15570/banking_lab
spring.datasource.username=postgres
spring.datasource.password=bankinglab

spring.jpa.hibernate.ddl-auto=update
